spring:
  application:
    name: vk-trigger-bot

server:
  port: ${PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info

vk:
  token: ${VK_GROUP_TOKEN:vk1.a.6vVLbtpBpohScuF6M4XAN8PHgFxlQYQxzoKosGQ0sKhQZM6FHJjsdIILnVqF7boPCuOizcKz0qRXx-1A8xuZ93ma9yttSRos0wQPHJdGpAkHG5LWSJmk1eCCbSw3pQQ2-dPqFsCSrQL9ybUa_HI7A1P7oz5x6ASz380MqwMh-9c8aK7SIEc97KBeGtZxugrhrwutXgpA7TyMzSfcEFyhOA}
  group-id: ${VK_GROUP_ID:235381622}
  api-version: ${VK_API_VERSION:5.199}
  trigger-word: ${VK_TRIGGER_WORD:сила}
  reply-text: ${VK_REPLY_TEXT:Привет! Вот твой файл 👋}
  already-sent-text: ${VK_ALREADY_SENT_TEXT:Файл уже был отправлен вам ранее.}
  non-member-text: ${VK_NON_MEMBER_TEXT:Привет, хочу отправить тебе материал "Где мои силы?", но у тебя нет подписки. Чтобы получить, подпишись на моё сообщество.}
  after-subscription-text: ${VK_AFTER_SUBSCRIPTION_TEXT:Вот твой файл}
  pdf-path: ${VK_PDF_PATH:classpath:files/Где_мои_силы_—_Анастасия_Гулина_психолог_КПТ.pdf}
  retry-delay: ${VK_RETRY_DELAY:PT3S}
  repeat-reply-cooldown: ${VK_REPEAT_REPLY_COOLDOWN:PT1M}
